### ISSUE TITLE
为何程序发送给服务器的refresh-token参数与启动时提供的参数不同

### ISSUE THREAD

**Issue by yuqiancn** [zxbu/webdav-aliyundriver#100]
linux 系统，使用mvn编译，v2.4.1版本，启动时的开始一部分如下：
[启动记录](https://gist.github.com/yuqiancn/28eb5bd656c8dbca5c58c3ae7e6e5567)

**Comment by yuqiancn** [comment]
Linux ###### 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

**Comment by yuqiancn** [comment]
用python试了一下，发送包含正确refresh-token的post request，能够获得我帐号的信息。所以是启动时有什么配置文件的优先级高于命令行参数么

**Comment by zxbu** [comment]
程序会自动维护一个token文件，如果token文件有效的会以这个为准

**Comment by yuqiancn** [comment]
所以这个文件默认是在jar文件同一目录下？

**Comment by yuqiancn** [comment]
请问我该怎么找到这个文件

**Comment by yuqiancn** [comment]
读代码找到了，在/etc/aliyun-driver/refresh-token

**Comment by yuqiancn** [comment]
建议修改逻辑，把命令行参数优先级放在配置文件前面。
