### ISSUE TITLE
能不能通过配置文件来设置ALIYUNDRIVE_REFRESH_TOKEN等

### ISSUE THREAD

**Issue by tingyue-wu** [zxbu/webdav-aliyundriver#101]
-e TZ="Asia/Shanghai" -e ALIYUNDRIVE_REFRESH_TOKEN="your refreshToken" -e ALIYUNDRIVE_AUTH_PASSWORD="admin" -e JAVA_OPTS="-Xmx1g"
这些参数能不能映射配置文件后，在文件里边修改
这样修改后只要重启容器就好。不需要token过期后又要重新建立容器

而且有了配置文件，还能支持多个阿里云账号，不知道下一版是否有这个考虑

**Comment by Gokou-Ruri** [comment]
指定`refresh-token`文件的路径就好，服务端启动时是优先读取`refresh-token`而不是执行参数里的token的。
e.g. ` --aliyundrive.work-dir="./aliyun-driver/"`

**Comment by zxbu** [comment]
本来就支持配置文件的，把容器里面的文件 /application.properties 挂载到外面，在里面填写对应的配置即可。
比如 
aliyundrive.refresh-token=xxxxxxx

**Comment by FoundAdd** [comment]
> 本来就支持配置文件的，把容器里面的文件/application.properties挂载到外面，在里面重新填写的配置文件。比如 aliyundrive.refresh -token=xxxxxxx

/application.properties 这个文件在根目录下吗？我直接启动容器没找到这个配置文件
