### ISSUE TITLE
refresh-token 路径指定的小BUG

### ISSUE THREAD

**Issue by Gokou-Ruri** [zxbu/webdav-aliyundriver#102]
我发现在Windows 10上用java8直接跑的情况下，参数里指定` --aliyundrive.work-dir=".\aliyun-driver\"`是无法运行的，会报错。必须改成` --aliyundrive.work-dir=".\aliyun-driver/"`才能正常运行，且此时`refresh-token`的路径也确实是在当前目录的子目录`aliyun-driver`下。

**Comment by zxbu** [comment]
发一下报错日志
