### ISSUE TITLE
建议提供单独sdk

### ISSUE THREAD

**Issue by bajie-git** [zxbu/webdav-aliyundriver#103]
大佬方便提供一个单独的sdk模块么，把阿里云盘客户端提取出来。
可以方便在项目中单独引用客户端，当前项目也可以应用模块更加清晰。

我已经参考源码提取出客户端了，但是过程还是有些麻烦的。在此提个建议望大佬采纳

**Comment by zxbu** [comment]
暂时没有这个计划
