### ISSUE TITLE
建议：能否增加树莓派的docker版本

### ISSUE THREAD

**Issue by liuminglm** [zxbu/webdav-aliyundriver#106]
我是树莓派4，4G内存版本，使用java版本，服务可以正常使用

但是速度最高只有3.5MB/S，看了下，树莓派cpu跑满了。试过通过树莓派做旁路由，速度能到20MB/S,所以应该是cpu性能不行

所以想问是否使用docker版本是不是性能好点，可以增加速度

**Comment by zxbu** [comment]
是否使用docker和性能关系不大
可自己通过docker build编译树莓派的docker版本
