### ISSUE TITLE
群晖的docker无法运行

### ISSUE THREAD

**Issue by liubangjian** [zxbu/webdav-aliyundriver#12]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:61: mounting "/volume1/docker/aliyundriver/etc/localtime" to rootfs at "/volume1/@docker/btrfs/subvolumes/5d05b3499190f04904e2f3d9f6def46f31a8ae3a0f097e979aaf1435555f540e/etc/localtime" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by zxbu** [comment]
你指定的 /volume1/docker/aliyundriver/etc/localtime 在宿主机不存在 ，改成 /etc/localtime
