### ISSUE TITLE
手机端有办法拿到refresh_token吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [zxbu/webdav-aliyundriver#126]
设备已root，有magisk/xposed，无电脑，有办法拿到阿里云盘的refresh_token吗？Android Chrome调试好像要依赖PC版本。
因为是用termux跑的，碰到过在正常运行中，token突然过期的情况，所以想问问有没有办法在手机端获取token。

**Comment by zxbu** [comment]
不太清楚手机端

**Comment by agutools** [comment]
同问

**Comment by a936919** [comment]
可以 我用的X浏览器 工具箱里面的开发者工具 就可以获取refresh_token
