### ISSUE TITLE
配合rclone时，java进程100%

### ISSUE THREAD

**Issue by shaojs321** [zxbu/webdav-aliyundriver#127]
vps配合rclone使用时，上传单个文件超大(大概>5G)时，后台java进程经常100%,导致rclone失效

**Comment by yugu91** [comment]
上传电影类建议使用cli, 可以激活秒传命令，基本都能匹配到相同文件而不需要耗费上传流量，rclone传10g以上我测试过会md5验证失败而不断重试，
[tickstep / aliyunpan](https://github.com/tickstep/aliyunpan)

**Comment by zxbu** [comment]
这个会受到 CPU、内存等硬件限制
