### ISSUE TITLE
长时间传输的时候速度会卡在600KB/s

### ISSUE THREAD

**Issue by HinataKato** [zxbu/webdav-aliyundriver#136]
![image](https://user-images.githubusercontent.com/57648531/143143590-8190e10b-fcda-43b9-8f13-043102c361eb.png)
刚开始的时候很快 过了一段时间就这样了 可能是阿里那边的限制？

**Comment by zxbu** [comment]
这个应该是你家庭宽带的限制

**Comment by HinataKato** [comment]
> 这个应该是你家庭宽带的限制

我刚才发现了 大概是因为我nginx的https代理
