### ISSUE TITLE
大佬，打扰一下，请问最近的log4j2漏洞会不会对软件有影响

### ISSUE THREAD

**Issue by Bili345679** [zxbu/webdav-aliyundriver#143]
大佬，打扰一下，请问最近的log4j2漏洞会不会对软件有影响。
软件好像用到了spring，spring又好像带有log4j2，解压jar包看到里面有log4j2的文件，因为没有相关知识，所以想问一下会不会被影响。

**Comment by zxbu** [comment]
理论上有影响，但接口有鉴权，实际影响不大。
我找时间修复一下log4j2版本号

**Comment by Bili345679** [comment]
大佬加油

**Comment by zxbu** [comment]
> 理论上有影响，但接口有鉴权，实际影响不大。 我找时间修复一下log4j2版本号

我看错了，本项目没有用到log4j等组件，不受此漏洞影响
