### ISSUE TITLE
另外经过使用发现，所有流量还是需要经过自己服务器

### ISSUE THREAD

**Issue by zouhy2001** [zxbu/webdav-aliyundriver#20]
也就是说阿里云盘像一块免费的大容量的盘，挂载在服务器下，存取速度取决于服务器？学生机带宽太小了，不太适合使用。
我以为像[CTList](https://github.com/iiiiiii1/CTList)一样，直接解析下载地址，流量不经过服务器，，，

**Comment by zxbu** [comment]
你场景用的不太合适， 如果是想做下载的，用CTList这种更合适的。
webdav-aliyundriver的场景，更适合和群晖等nas系统在一起，做本地文件的自动同步
