### ISSUE TITLE
post /file/list 方法能否做下缓存

### ISSUE THREAD

**Issue by hetaoos** [zxbu/webdav-aliyundriver#21]
您好，感谢提供该工具。

我把WebDav作为群晖 Hyper Backup 备份目标位置时，
可能是每上传完成一个文件，都会刷新目录内的文件列表，而目录里面的文件又非常多。导致 **post /file/list** 调用非常频繁，大概每上传一个文件，需要调用50次以上。
<img width="1072" alt="捕获" src="https://user-images.githubusercontent.com/1094462/125968668-970b1148-11b1-443d-ad8f-2782b961701b.PNG">

能否对获取文件列表的方法做下缓存，比如在只是上传或者更新文件后，获取文件列表时，只刷新第一页，其他沿用之前的缓存。

**Comment by zxbu** [comment]
我后面看下是否可以优化，问题先记下了

**Comment by zxbu** [comment]
已优化，更新一下

**Comment by hetaoos** [comment]
谢谢。昨晚已经更新。效果不错。
