### ISSUE TITLE
前端美化

### ISSUE THREAD

**Issue by zxbu** [zxbu/webdav-aliyundriver#24]
目前直接用浏览器打开的页面，比较简陋，也缺少直连下载等功能。 

1. 后端增加Controller层，封装相关api（列表、直连下载等），底层service都是现成的，只需要封装一下转成http api
2. 开发一套前后端分离的前端站点

如果感兴趣的朋友，可与我联系

**Comment by RyanGongWolf** [comment]
这是webdev  为啥用浏览器？

**Comment by yuqiancn** [comment]
浏览器考虑下油猴脚本/浏览器插件？
