### ISSUE TITLE
请问下端口是仅限本地访问？

### ISSUE THREAD

**Issue by etrock99** [zxbu/webdav-aliyundriver#26]
本地8080访问OK的，路由端做NAT进来，如 Router:25-->LAN 192.168.222.99:8080
试了好多遍，确定链路是通的，可以外网 telnet WAN的25-->8080，看到
`
HTTP/1.1 400
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 435
Date: Sun, 25 Jul 2021 06:42:41 GMT
Connection: close

<!doctype html><html lang="en"><head><title>HTTP Status 400 鈥?Bad Request</title><style type="text/css">body {font-fam
ily:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 鈥?Bad Request</h1></body></html>

遗失对主机的连接。
C:\Users\Etrock>
`

是这种访问不能NAT的是吧？

**Comment by zxbu** [comment]
不限制本地访问。
你这个应该是网络设置问题，你可以进群和大家交流

**Comment by etrock99** [comment]
额。。。看起来是Chrome的锅，并不是不能访问，是提示“ERR_UNSAFE_PORT”

浏览器快捷方式加 --explicitly-allowed-ports=xxx 后，外网可以访问到NAS的http端了~
RaiDrive确实好用，感谢
![QQ截图20210725163322](https://user-images.githubusercontent.com/9324349/126892966-4a1c3529-bc8f-400f-874a-17eadb393bb1.png)
![QQ截图20210725163337](https://user-images.githubusercontent.com/9324349/126892968-affa9675-34fc-4b48-814f-947284f8ed98.png)
![QQ截图20210725163355](https://user-images.githubusercontent.com/9324349/126892969-c6a7209f-c8d5-4638-879a-c16f97f13576.png)

**Comment by zxbu** [comment]
一般不会把端口设置这么小，如果开外网的话，建议把端口改成大一些的，比如4万+
这样也可以降低被端口扫描的概率

**Comment by etrock99** [comment]
> 一般不会把端口设置这么小，如果开外网的话，建议把端口改成大一些的，比如4万+
> 这样也可以降低被端口扫描的概率

唉，公司坑爹防火墙策略，只允许部分常用端口出去，是出方向。。。无可奈何的选择
