### ISSUE TITLE
请问docker安装后，有将webdav挂载到本地目录的内部变量可以设置吗？

### ISSUE THREAD

**Issue by jimmywong-git** [zxbu/webdav-aliyundriver#30]
您好! 群晖使用docker挂载后，webdav无法直接添加进索引文件夹，需要使用本地目录才能够添加，请问有什么方法或者变量能够将webdav映射成本地目录？谢谢！

**Comment by zxbu** [comment]
群晖的FileStation可以直接挂载的，具体你可以网上查查或进群交流

**Comment by jimmywong-git** [comment]
嗯 挂载是可以，但是如果需要群晖的索引服务就添加不了了好像， 我的想法是将webdav挂载后，添加进索引文件夹，然后使用Audio Station直接读取Aliyun中的文件
