### ISSUE TITLE
电脑直接卡死

### ISSUE THREAD

**Issue by L1cardo** [zxbu/webdav-aliyundriver#31]
webdav-aliyundriver 运行在nas，然后将目录挂在在本地的Mac上，直接卡死了
是我的电脑性能问题还是webdev的问题呀？

<img width="492" alt="image" src="https://user-images.githubusercontent.com/33802186/127736446-7323ab11-b6b9-4c2c-80f8-0c293eecdd49.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/33802186/127736449-888347e9-5ff1-494d-96d0-0324784e9e9f.png">

**Comment by zxbu** [comment]
是最新版本吗？

**Comment by L1cardo** [comment]
今天刚拉取的docker镜像

我的阿里云盘是满的状态  不知道是不是这个原因

**Comment by zxbu** [comment]
请试一下最新版本还有无此问题，并注意文件名不能包含 / 符号
