### ISSUE TITLE
请求失败，part_info_list无效

### ISSUE THREAD

**Issue by tcwj2008** [zxbu/webdav-aliyundriver#33]
请教一下，使用WIN+RaiDrive，webdav-aliyundriver使用docker搭建，可以下载不能上传，后台日志如下

`2021-08-03 17:21:49.552  INFO 1 --- [nio-8080-exec-2] c.g.z.w.store.AliYunDriverClientService  : 开始上传文件，文件名：/aaa.txt，总大小：0, 文件块数量：0`
`2021-08-03 17:21:49.672  INFO 1 --- [nio-8080-exec-2] c.g.z.w.client.AliYunDriverClient        : post /file/create_with_proof, body {"check_name_mode":"refuse","content_hash":null,"content_hash_name":"none","drive_id":"893454","name":"aaa.txt","parent_file_id":"root","proof_code":null,"proof_version":"v1","size":0,"part_info_list":[],"type":"file"}, code 201`
`2021-08-03 17:21:49.676  INFO 1 --- [nio-8080-exec-2] c.g.z.w.store.AliYunDriverClientService  : 文件预处理成功，开始上传。文件名：/aaa.txt，上传URL数量：1`
`2021-08-03 17:21:49.742  INFO 1 --- [nio-8080-exec-2] c.g.z.w.client.AliYunDriverClient        : post /file/get_upload_url, body {"drive_id":"893454","part_info_list":[],"file_id":"61090aad530843b49e8b42a2a46e9ee807edb8f0","upload_id":"D20D09D5FBB249D7BA0364460AD4F264"}, code 400`
`2021-08-03 17:21:49.742 ERROR 1 --- [nio-8080-exec-2] c.g.z.w.client.AliYunDriverClient        : 请求失败，url=/file/get_upload_url, code=400, body={"code":"InvalidParameter.PartInfoList","message":"The input parameter part_info_list is not valid. part_info_list is required"}`

**Comment by zxbu** [comment]
文件大小是不是为0？
