### ISSUE TITLE
能否为Jar包运行添加配置文件功能？

### ISSUE THREAD

**Issue by wuhgit** [zxbu/webdav-aliyundriver#35]
我当前是通过 Systemd 的方式使用这个 Jar ，因为还要配合 Rclone 将其挂载到本地目录，开机即用比较方便，但目前遇到了一些问题。

在写 systemd 配置的时候，我把诸如 `--aliyundrive.refresh-token` 等参数一并写了进去，如果偶尔长时间不开机，下一次启动的时候就会遇到token失效的情况，每当这时就需要重新编辑这个 systemd 配置，保存、重载、重新启动服务。

请问开发者能否为 Jar 运行添加一个配置文件功能呢？将这些附带参数全部存储在一个配置文件中，运行的时候只需要类似这样的命令：

```
java -jar webdav.jar --conf=<conf_file_loc>
```

即可，这样在当再次遇见token失效的时候，我只需要修改配置文件，然后直接重启服务就可以了。

谢谢！

**Comment by zxbu** [comment]
参考这种写法
java -jar -Dspring.config.location=<conf_file_loc> webdav.jar
