### ISSUE TITLE
使用Dolphin创建文件夹的时候出现问题

### ISSUE THREAD

**Issue by southcat** [zxbu/webdav-aliyundriver#37]
![image](https://user-images.githubusercontent.com/32999518/128677306-c0027033-10f0-4544-8049-4469cd3a4a86.png)

**Comment by southcat** [comment]
如图在不断地显示新建文件夹，最后我手动ctrl+c结束的

**Comment by zxbu** [comment]
应该是客户端兼容性问题，换一个其他客户端试试
