### ISSUE TITLE
英文符号引起400错误

### ISSUE THREAD

**Issue by ghostry** [zxbu/webdav-aliyundriver#40]
2015 一拳超人 [HYSUB]ONE PUNCH MAN[S1+S2][BDrip][BIG5_MP4][1920X1080]

类似这种文件名,浏览器访问时有出现400错误.

版本是 当前 docker 的 latest

**Comment by zxbu** [comment]
发一下完整的文件名。 有没有/

**Comment by ghostry** [comment]
> 发一下完整的文件名。 有没有/

http://192.168.x.x:8xx/%E5%8A%A8%E6%BC%AB/%E5%89%A7%E9%9B%86/2015%20%E4%B8%80%E6%8B%B3%E8%B6%85%E4%BA%BA%20[HYSUB]ONE%20PUNCH%20MAN[S1+S2][BDrip][BIG5_MP4][1920X1080]/

**Comment by zxbu** [comment]
这是个前端页面渲染时的bug，不影响webdav协议，只影响网页。 后续安排修复

**Comment by zxbu** [comment]
已修复
