### ISSUE TITLE
启动时指定端口无效

### ISSUE THREAD

**Issue by skywoodlin** [zxbu/webdav-aliyundriver#42]
1. 环境和版本
    win10, IDEA自己打包的最新版2.2.0， 代码中仅添加了`refreshToken` (AliYunDriveProperties:9), 双击`spring-boot:build-image`生成的jar包

2. 步骤

> 1. 改名为webdav.jar
> 2. cd到相应目录下执行： `java -jar webdav.jar --server.port 53488`
> 3. log中打印： `Tomcat initialized with port(s): 8080 (http).....`
> 4. 使用RaiDrive连接8080端口， 后续正常。

**Comment by zxbu** [comment]
关于自定义端口的问题，请查询 spring boot相关文档

**Comment by skywoodlin** [comment]
已解决， `java -jar webdav.jar --server.port=53488`
