### ISSUE TITLE
有没有大佬写一个独立的EXE文件，直接挂载到本地的

### ISSUE THREAD

**Issue by chenlu96** [zxbu/webdav-aliyundriver#43]
有没有大佬写一个独立的EXE文件，直接挂载到本地的，希望有java大佬帮忙封装一下

**Comment by fred913** [comment]
建议java+raidrive

**Comment by Beginner-yms** [comment]
阿里云好像出了桌面端，可以直接用官方

**Comment by coderykw** [comment]
求 本地电脑 一键部署 ，服务器速度太慢 撑不住

**Comment by Dr-Victor** [comment]
直接rclone把webdav挂到本地也可

**Comment by longhuan1999** [comment]
webdav-aliyundriver只是让阿里云盘变身为webdav协议的文件服务器，挂载还是需要配合客户端使用的。但可以将webdav-aliyundriver安装成Windows服务，实现开机自启、后台运行，可以试试这个https://github.com/longhuan1999/webdav-aliyundriver/releases/tag/win1.1.0
