### ISSUE TITLE
之前好好的，这几天列不出文件了

### ISSUE THREAD

**Issue by czahoi** [zxbu/webdav-aliyundriver#47]
用的docker版，
rclone:
```
~# gclone lsd webdav:
2021/08/17 13:42:59 ERROR : : error listing: couldn't list files: EOF
2021/08/17 13:42:59 Failed to lsd with 2 errors: last error was: couldn't list files: EOF
```
raidrive打开文件夹是空白页

**Comment by daveccc** [comment]
同样的问题

**Comment by microgorgage** [comment]
你的邮件我已经收到，我会尽快查阅！

**Comment by daveccc** [comment]
我现在觉得不是文件名的问题。当时根目录有一个英文名的文件夹。我新建了一个中文名文件夹，转存了一些分享的目录。然后发现中文的目录不显示在其下的所有文件，可以新建，但是也群晖的file
station里也看不到，就是一个空目录。英文的正常。所以我以为是文件名或者缓存的问题。但是后来发现，在中文文件夹默认排序的第一个子文件夹的大小不对，删除这个文件夹后，中文的文件夹正常刷新。
当时没有截图，不知我说清楚了没有。
我发现这个特别适合放在vps上把阿里的转到google drive上，放群晖上在加拿大这边也就能跑到5m。还没试，回头试一下。
感谢您的辛苦劳动，加油。

zxbu ***@***.***> 于2021年12月8日周三 19:08写道：
