### ISSUE TITLE
web访问路径带空格报错404

### ISSUE THREAD

**Issue by WinteWu** [zxbu/webdav-aliyundriver#48]
如 
![image](https://user-images.githubusercontent.com/16253120/129832278-04279dc9-e07d-4743-91e5-877208b1571a.png)
应该url路径为
![image](https://user-images.githubusercontent.com/16253120/129832346-e9d8a887-9e4c-46a5-b3c1-8a1ecac09c69.png)

**Comment by WinteWu** [comment]
具体代码没细看, 不太懂webdav api, 是不是修改一下normalizingPath方法就可以?

**Comment by zxbu** [comment]
你用的不是最新版本吧，已经修复了

**Comment by WinteWu** [comment]
> 你用的不是最新版本吧，已经修复了

好吧. 我用的是docker镜像

**Comment by zxbu** [comment]
重新docker pull一下最新的

**Comment by WinteWu** [comment]
![image](https://user-images.githubusercontent.com/16253120/130578248-8cb46aa2-6f4b-44cc-928d-52a0e0bb6028.png)
刚刚重新pull了, 但是还是异常 404

**Comment by WinteWu** [comment]
![image](https://user-images.githubusercontent.com/16253120/130581778-1ff8f764-a75f-406a-8e4a-7182fccc88a2.png)
add: digest
