### ISSUE TITLE
centos7 挂载磁盘后，使用vi新建文件无法保存

### ISSUE THREAD

**Issue by lengyuxuan** [zxbu/webdav-aliyundriver#49]
Aug 18 18:39:37 g4 java[20888]: 2021-08-18 18:39:37.766 ERROR 20888 --- [io-17080-exec-2] net.sf.webdav.WebDavServletBean          : Exception: java.lang.NullPointerException
Aug 18 18:39:37 g4 java[20888]: at net.sf.webdav.methods.DoLock.doNullResourceLock(DoLock.java:213)
Aug 18 18:39:37 g4 java[20888]: at net.sf.webdav.methods.DoLock.doLock(DoLock.java:137)
Aug 18 18:39:37 g4 java[20888]: at net.sf.webdav.methods.DoLock.execute(DoLock.java:115)
Aug 18 18:39:37 g4 java[20888]: at net.sf.webdav.WebDavServletBean.service(WebDavServletBean.java:131)
Aug 18 18:39:37 g4 java[20888]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Aug 18 18:39:37 g4 java[20888]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Aug 18 18:39:37 g4 java[20888]: at com.github.zxbu.webdavteambition.filter.ErrorFilter.doFilterInternal(ErrorFilter.java:39)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
Aug 18 18:39:37 g4 java[20888]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
Aug 18 18:39:37 g4 java[20888]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
Aug 18 18:39:37 g4 java[20888]: at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
Aug 18 18:39:37 g4 java[20888]: at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
Aug 18 18:39:37 g4 java[20888]: at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
Aug 18 18:39:37 g4 java[20888]: at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
Aug 18 18:39:37 g4 java[20888]: at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Aug 18 18:39:37 g4 java[20888]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Aug 18 18:39:37 g4 java[20888]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Aug 18 18:39:37 g4 java[20888]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Aug 18 18:39:37 g4 java[20888]: at java.lang.Thread.run(Thread.java:748)

**Comment by zxbu** [comment]
用的什么客户端？

**Comment by lengyuxuan** [comment]
直接编译的jar包
编译： mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
启动：java -jar webdav-aliyundriver-2.2.0.jar --aliyundrive.refresh-token="xxxxxxxxxxxxxx" --server.port=17080
挂载：mount -t davfs http://192.168.8.60:17080/ /aliyun

**Comment by lengyuxuan** [comment]
> 用的什么客户端？

直接编译的jar包
编译： mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
启动：java -jar webdav-aliyundriver-2.2.0.jar --aliyundrive.refresh-token="xxxxxxxxxxxxxx" --server.port=17080
挂载：mount -t davfs http://192.168.8.60:17080/ /aliyun

**Comment by zxbu** [comment]
用rclone客户端兼容性更好些
