### ISSUE TITLE
if any possible to support rapid upload ?

### ISSUE THREAD

**Issue by 906675869** [zxbu/webdav-aliyundriver#56]
I have watched all your api code about the fuc of aliyundrive but find that it's just upload any file as it is a new file ,but it always cost a lot time.cal it's sha and upload rapid could be a better way.but I also find it's protect by proof code . if there are any way to this , I'll be thankful.  

waiting for your reply .

**Comment by zxbu** [comment]
Webdav protocol , Maybe no way to support rapid upload.

Because, cal file sha need total file , but webdav-aliyundriver server use streaming upload. 
if webdav-aliyundriver server tmp save total file, This will increase a lot of costs(network、cpu、disk)
It my be more harm than rapid upload.
