### ISSUE TITLE
稍大的文件分片后，经常性的存在多轮重复上传问题

### ISSUE THREAD

**Issue by mageia** [zxbu/webdav-aliyundriver#58]
容器在腾讯云vps上跑，资源配置尚可，请问这可能是哪里的问题？

![image](https://user-images.githubusercontent.com/10463781/130351076-54471db5-e67f-4cbe-9a61-61d4bda89c58.png)

**Comment by zxbu** [comment]
上传速度多少？

**Comment by mageia** [comment]
![image](https://user-images.githubusercontent.com/10463781/130596186-51add14a-154e-4ba3-aaff-de1a1acf2d6f.png)


速度感觉还凑合，把并发上传任务数设为3，上传速度波动比较大。并发任务数大的时候，这个现象更明显

**Comment by zxbu** [comment]
用的是最新版本吗

**Comment by mageia** [comment]
![image](https://user-images.githubusercontent.com/10463781/130707638-c6f407c0-6f22-41d8-9b51-f7293c663c13.png)

前几天pull的版本

**Comment by zxbu** [comment]
之前出现过这个问题，我已经修复了。现无法重现
