### ISSUE TITLE
多线程优化

### ISSUE THREAD

**Issue by Sheey11** [zxbu/webdav-aliyundriver#59]
- 环境: macOS 使用 Finder 挂载

随便传了一个文件夹（app, 不大但是文件多）

![截屏2021-08-23 上午10 37 32](https://user-images.githubusercontent.com/13375959/130382450-cb1aa39e-23d0-4a5f-9344-5934c2487883.png)

在带宽足够的情况下，跑了 10 分钟还没跑完

**Comment by zxbu** [comment]
是否多线程上传取决于客户端，不是 webdav-aliyundriver
webdav-aliyundriver本身是支持多线程的
