### ISSUE TITLE
之前都正常，今天试了下，拷贝文件会出错

### ISSUE THREAD

**Issue by wdy3334** [zxbu/webdav-aliyundriver#6]
比如说我的网盘里有个aaa的文件夹，我往里面拷贝一个bbb.mp4的文件，这个aaa文件夹名字就会变成aaa.mp4，而且文件夹内部也会有一个0kb的aaa.mp4，还会在根目录下生成一个error_当前日期_当前时间的文件（文件大小和aaa.mp4一样）

**Comment by wdy3334** [comment]
忘了说了，我是把网盘挂载在我的电脑上，系统win10

**Comment by zxbu** [comment]
这个bug在2.x版本已经修复（仅支持阿里云盘）
