### ISSUE TITLE
上传出现文件夹重复创建的情况

### ISSUE THREAD

**Issue by ghostry** [zxbu/webdav-aliyundriver#60]
使用环境

服务端 webdav-aliyundriver 为 docker latest

客户端 rclone v1.56.0

上传使用 rclone copy 命令，从本地copy到云盘。

包含内容的新文件夹会出现重复创建的情况，出现频率是经常。

**Comment by zxbu** [comment]
webdav-aliyundriver 没有判断文件夹是否重复。 rclone copy命令本身就是全量复制，所以会导致这个问题。
你可以使用 rclone sync命令，可避免这个问题
或者等我有时间修复一下

**Comment by ghostry** [comment]
> webdav-aliyundriver 没有判断文件夹是否重复。 rclone copy命令本身就是全量复制，所以会导致这个问题。
> 你可以使用 rclone sync命令，可避免这个问题
> 或者等我有时间修复一下

sync应该不行，我是做备份，网盘保存所有文件，本地会删除旧文件。

重复创建的情况经常出现在有内容的新文件夹拷贝的时候，有时创建2个，有时3，4个

我怀疑是不是时差问题，rclone应该是先创建文件夹，然后写入文件夹下文件。这中间有个时差。

如果是有小文件操作非常快的话，创建文件夹成功的消息未能及时收到，前边创建文件夹和紧跟着的几个小文件上传动作，都会导致文件夹的创建动作。

**Comment by eritpchy** [comment]
+1

**Comment by FleyX** [comment]
rclone默认并发数是4，导致一次性创建多个文件夹了，最好把并发数改成1，加入如下参数：
```bash
 --transfers=1
```
并发数大于1，除了重复创建文件夹的问题，偶尔还会报错` Failed to copy: object not found`

**Comment by ghostry** [comment]
> rclone默认并发数是4，导致一次性创建多个文件夹了，最好把并发数改成1，加入如下参数：
> 
> ```shell
>  --transfers=1
> ```

这个方法有效

**Comment by HengyueLi** [comment]
> 

想了解一下这个方式会不会降低效率？或者说该项目支不支持大并发数？

**Comment by FleyX** [comment]
> > 
> 
> 想了解一下这个方式会不会降低效率？或者说该项目支不支持大并发数？
> 
> > rclone默认并发数是4，导致一次性创建多个文件夹了，最好把并发数改成1，加入如下参数：
> > ```shell
> >  --transfers=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并发数大于1，除了重复创建文件夹的问题，偶尔还会报错` Failed to copy: object not found`

几KB的小文件很多的话，开并发效率会高点，否则差不多。
阿里云盘自身是允许文件夹重名的，所以开并发创建空文件夹很难避免
