### ISSUE TITLE
关于打开软件闪退

### ISSUE THREAD

**Issue by Spturate** [zxbu/webdav-aliyundriver#62]
我修改好token后无论是开管理员模式还是不开，打开insall.exe后会直接闪退，换其他JRE启动也一样，然后点卸载提示我没安装服务
![image](https://user-images.githubusercontent.com/30800649/130668290-c2418a31-c31d-4ffd-8510-c21f2e4ffa2c.png)
![image](https://user-images.githubusercontent.com/30800649/130668210-ba4171a1-f91a-41d3-bd61-7ccc7ff4a3ed.png)

**Comment by zxbu** [comment]
你使用的这个东西不是我维护的，issues提错地方了
