### ISSUE TITLE
建议增加日志控制功能

### ISSUE THREAD

**Issue by Li-Lian1069** [zxbu/webdav-aliyundriver#65]
可以添加一个日志输出的开关或者日志等级过滤的功能，不如每天跑很多日志浪费io性能占用磁盘空间

**Comment by zxbu** [comment]
可以通过配置自行调整，这是自带的功能.
例如添加环境变量 LOGGING_LEVEL_ROOT=warn
可只保留错误日志输出

**Comment by Gokou-Ruri** [comment]
> 可以通过配置自行调整，这是自带的功能.
> 例如添加环境变量 LOGGING_LEVEL_ROOT=warn
> 可只保留错误日志输出

请问这个是指编译时的环境变量吗？用release的包无法修改控制日志输出吗？

**Comment by zxbu** [comment]
> > 可以通过配置自行调整，这是自带的功能.
> > 例如添加环境变量 LOGGING_LEVEL_ROOT=warn
> > 可只保留错误日志输出
> 
> 请问这个是指编译时的环境变量吗？用release的包无法修改控制日志输出吗？

运行时可指定
