### ISSUE TITLE
请问一下搭建好webdav服务之后，可以使用多个设备同时登录同一个账号么

### ISSUE THREAD

**Issue by fusang1337** [zxbu/webdav-aliyundriver#71]
场景是
1、NAS搭建好的webdav服务
2、局域网内多个设备需要挂载使用

谢谢大佬

**Comment by Ivens-Zhang** [comment]
我使用过程中是没问题的，比如我正在用群晖的 cloud sync 同步，又使用浏览器访问，这和你说的多个设备挂载是同样的，只是同时上传不知道能否保证数据的正确性了。因为都是通过容器挂上了阿里云盘，而且同时登录数量没有做限制，以上是我个人理解，你可以试着挂载一下。

**Comment by zxbu** [comment]
可以的
