### ISSUE TITLE
Armbian系统挂载webdav报如下错误

### ISSUE THREAD

**Issue by cryboy007** [zxbu/webdav-aliyundriver#73]
![image](https://user-images.githubusercontent.com/38103600/131461779-07720e7e-7678-43c6-9f4f-1db4127cd2e3.png)
/sbin/mount.davfs: user davfs2 does not exist

**Comment by zxbu** [comment]
davfs的用法可以去网上找找教程

**Comment by cryboy007** [comment]
嗯嗯
