### ISSUE TITLE
如何登陆多账号？

### ISSUE THREAD

**Issue by Calmact** [zxbu/webdav-aliyundriver#75]
请问如何登陆多个云盘账号？端口和Tocken应该怎么设置？
尝试添加新的端口和Tocke你没有成功。

**Comment by zxbu** [comment]
运行多个，把token挂载位置和端口区分开。 
具体可加群交流

**Comment by Calmact** [comment]
已加，请群主通过
···
群号（已满）：789738128
二群群号：979024890···

**Comment by Calmact** [comment]
请问端口和挂在应该怎么修改呢？写在这里可以更多需要的人看到。
```
-p 8081:8081  -v /etc/localtime:/etc/localtime -v /etc/aliyun-driver/:/etc/aliyun-driver/
