### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by HtnrxUNc** [zxbu/webdav-aliyundriver#76]
我成功的使用docker拉取并将程式跑了起来
我调整了参数中的端口，token与内存大小
途中任何东西都没有报错阻止我的任何运行
我也已经查看到端口被占用
但当我尝试访问时，我却无法使用ip:port的形式访问
我的chrome提示我

> 该网页无法正常运作
>    * 未发送任何数据。
>  ERR_EMPTY_RESPONSE

**Comment by Joyist2021** [comment]
确实很大问题

**Comment by zxbu** [comment]
使用方面可进群交流
