### ISSUE TITLE
问一下，这个webdav为啥走的是服务器流量呢

### ISSUE THREAD

**Issue by eicky** [zxbu/webdav-aliyundriver#77]
我手机用nPlayer连接，然后抓包，发现是走的服务器流量，并不是阿里云盘的流量。。。

**Comment by tengxunkuku** [comment]
很简单啊，你网盘挂载服务器上，然后手机连接webdav，使用服务器流量进行中转。这和网盘列表程序直接与网盘进行通信是不同的

**Comment by zxbu** [comment]
服务器流量做中转
