### ISSUE TITLE
阿里云盘的回收站中，有很多大小为0的文件

### ISSUE THREAD

**Issue by icyomik** [zxbu/webdav-aliyundriver#86]
使用的是webdav-2.4.1.jar包，挂载到本地硬盘分区后，使用Beyond Compare进行同步。
发现当云盘没有当前文件时，同步过去之后会在云盘的回收站中出现同名的大小为0的文件。
自测使用其他软件CloudDrive挂载的话并没有这个问题，请开发大大有时间后帮忙修正，谢谢。

**Comment by 011011100010110101101111** [comment]
> 这个是已知问题，webdav协议上传的时候会先上传一个空文件，然后再上传文件本体。

在Linux 下 cp 进去不会有问题，在mac 通过命令cp 进去会有一个._ 开头的同名隐藏文件，rm 删除文件后，该文件会同步删除
