### ISSUE TITLE
同步文件到云盘中，对应文件的修改时间不对

### ISSUE THREAD

**Issue by icyomik** [zxbu/webdav-aliyundriver#87]
使用的是webdav-2.4.1.jar包，挂载到本地硬盘分区后，使用Beyond Compare进行同步。
比如本地文件A的修改时间为17年04月，但同步至云盘后的文件修改时间却为当前时间。
该情况导致使用对比软件（或命令）无法根据修改时间进行同步（当修改前后大小一致时）
不确认是云盘的原因，还是开发大大WebDav协议实现导致，请有空时帮忙看看，谢谢。

**Comment by zxbu** [comment]
文件同步的时候，无法指定修改时间。 你可以试一下，直接通过官方客户端上传，应该也显示为当前时间
