### ISSUE TITLE
docker版本，如果有2个网卡，webdav就打不开

### ISSUE THREAD

**Issue by PHCSJC** [zxbu/webdav-aliyundriver#89]
我有2个网卡，br0和br1，docker版本启动后访问不了，提示网页不存在，但telnet端口其实是通的。另外，另一个机器只有一个网卡，docker版本完全正常，没有任何问题。

系统是debian 10，docker版本是9月8号最新的这个。

再另外，我用jar包是可以的，就是docker不行，再请问jar包启动时如何限制内存？

**Comment by zxbu** [comment]
这个和项目没关系，网络技术问题可以在网上查查，或进群交流

**Comment by PHCSJC** [comment]
我的系统里有多个docker container，都没有问题，就你这个不行，所以我怀疑是你的容器的问题，所以来反馈下，当然我也再检查下我的系统问题
