### ISSUE TITLE
refreshToken被服务端加密了？

### ISSUE THREAD

**Issue by 2045ga** [zxbu/webdav-aliyundriver#90]
refreshToken貌似不见了  时间2021年9月13日

**Comment by q240627995** [comment]
我刚刚看还有。

**Comment by yuqiancn** [comment]
9月13日21:00,webdav-aliyundriver请求refresh_token失败，我以为是我refersh_token错了，换了新的还是错误400。wireshark抓包看了一下，网页版登录的时候已经不再给websv.aliyundrive.com发送请求了，倒是网页版登录上去180秒左右从websv.aliyundrive.com服务器下发5个加密的包。

**Comment by yuqiancn** [comment]
wireshark没办法对ssl解包，不知道是不是我使用方式的问题

**Comment by amwwcw0101** [comment]
我也用不了了

**Comment by gongkaixiong** [comment]
啊，刚下载想体验一下 ，结果就发现refresh_token 没了

**Comment by 2045ga** [comment]
> 啊，刚下载想体验一下 ，结果就发现refresh_token 没了

按F12打开开发者工具，**点击Application，点击Local Storage，点击Local Storage，点击Local Storage，点击 Local Storage**下的
不是cookie
