### ISSUE TITLE
云盘的文件挂载到本地后只能读取下载，不能写入和修改

### ISSUE THREAD

**Issue by ChiehJang** [zxbu/webdav-aliyundriver#91]
ubuntu20.04 docker下按照文档部署，利用nginx反向代理后实现域名访问、挂载等都是正常的，但是在mac上不管是cmd+K直接连接服务器还是用第三方软件就行挂载webdav都不能写入和修改文件，试过再windows上、手机上也同样不能写入。

**Comment by hugoyue** [comment]
单向同步，只有读取权限

**Comment by zxbu** [comment]
无法判断问题，具体使用问题可加群交流
