### ISSUE TITLE
在termux下运行时，无法读取到refresh-token

### ISSUE THREAD

**Issue by Gokou-Ruri** [zxbu/webdav-aliyundriver#95]
termux的etc目录在/usr目录下，所以路径是 `/data/data/com.termux/files/usr/etc/aliyun-driver/refresh-token`

log里显示 `读取refreshToken文件 /etc/aliyun-driver/refresh-token 失败:`
每次运行jar服务端以前还得先执行一次proot才行，有点麻烦。能不能让服务端读取 `/etc/aliyun-driver/refresh-token` 失败以后去读取`/data/data/com.termux/files/usr/etc/aliyun-driver/refresh-token`？

**Comment by zxbu** [comment]
通过这个参数可以自定义路径
--aliyundrive.work-dir=/etc/aliyun-driver/
    token挂载路径

**Comment by Gokou-Ruri** [comment]
> 通过这个参数可以自定义路径
> --aliyundrive.work-dir=/etc/aliyun-driver/
> token挂载路径

感谢解答！
