### ISSUE TITLE
请问现在是不是不支持arm v8？

### ISSUE THREAD

**Issue by rewei** [zxbu/webdav-aliyundriver#96]
我在Cortex-A55的盒子上安装（docker方式），提示：docker: no matching manifest for linux/arm/v8 in the manifest list entries.

cpu参数如下：
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               0
Model name:          Cortex-A55
Stepping:            r1p0
CPU max MHz:         1908.0000
CPU min MHz:         100.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp

**Comment by zxbu** [comment]
可采用java运行的方式
